LiarGame Subject Select View & LiarGame View early Setup
2jae6/LiarGame pull request #12
Opened 2022-04-25 16:20 UTC by 2jae6

## 배경
라이어 게임 주제 선택 이후 라이어 게임까지 갈 수 있는 화면을 초기 구성이 필요하였습니다.

## 목적
LiarGame Subject Select View & LiarGame View early Setup

## 리뷰 시 참고사항
- 아직 초기 뷰 그리는 단계라서 코드가 아키텍쳐나 문법이나 위치에 맞는지 확인해주시면 감사드리겠습니다.

2022-04-25 17:02 UTC, elppaaa requested changes

2022-04-25 17:02 UTC, elppaaa commented on LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
> +    let flexLayoutContainer: UIView = UIView()
접근 제어 `private` 해주면 좋을것 같아용

2022-04-25 17:02 UTC, elppaaa commented on LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
> +    let jobButton: UIButton = UIButton()
이 친구들도 외부에서 아직 참조하지 않는 것 같아요. 밑에 `setupViews()` 도 `private` 해주면 좋을 것 같아요

2022-04-25 17:02 UTC, elppaaa commented on LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
> +            $0.setTitleColor(.black, for: .normal)
잘못된건 아닌데, 중복되는 코드는 줄이면 더욱 좋을 것 같아요.

```swift
fileprivate func makeButton(str: String) -> UiButton { 
  let button = UIButton()
  button.backgroundColor = .yellow
  $0.setTitle(str, for: .normal)
  $0.setTitleColor(.black, for: .normal)
  return button
```

취향입니다. 잘못된 부분은 아니에요 (˃̣̣̣̣︿˂̣̣̣̣ )

2022-04-25 17:02 UTC, elppaaa commented on LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
> +        animalButton.rx.tap.asDriver()
내부 동작은 UI 작업도 아니고 굳이 메인 스레드에서 동작될 이유가 없어 보입니다. 혹시 `drive` 로 동작하게 하신 이유가 있을까요?

2022-04-25 17:02 UTC, elppaaa commented on LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
> +        }).disposed(by: disposeBag)
`reactor.state` 는 `selectedSubject` 외 다른 값이 변경 될 때도 방출됩니다. 따라서 다른 state 가 변경되었을때도 의도치 않게 해당 코드가 동작할 수 있어요. 지금은 `State` 에 프로퍼티가 하나라 문제는 없어 보입니다. :] 또 무조건 한번만 실행될 부분이라 문제 없네용

`nil` 무시는 `.compactMap { $0 }` 또는 `.filter { $0 != nil }` 로 가능합니다. 😄 


```swift
      reactor.state.map(\.selectedSubject)
        .compactMap { $0 }
        .distinctUntilChanged()
        .withUnretained(self)
        .subscribe(onNext:{ `self`, subject in
            let liarGameVC = LiarGameViewController(subject: subject)
            liarGameVC.modalPresentationStyle = .fullScreen
            self.present(liarGameVC, animated: true, completion: nil)
        }).disposed(by: disposeBag)
```

2022-04-25 19:39 UTC, elppaaa commented on LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
> +            $0.setTitleColor(.black, for: .normal)
__FlexLayout__ 에서 레이아웃을 정의할 때에 `flex.addItem()` 메서드에서 `addSubView` 가 호출됩니다. 굳이 추가하지 않아도 될 것 같네요 ! 충돌날 수도 있구요 !

2022-04-26 02:58 UTC, 2jae6 commented on LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
> +    let flexLayoutContainer: UIView = UIView()
기본적으로 Private 프로퍼티에 제한되도록 수정하였습니다 :)

2022-04-26 02:59 UTC, 2jae6 commented on LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
> +    let jobButton: UIButton = UIButton()
마찬가지로 메서드에도 private 추가해주었습니다.

2022-04-26 03:00 UTC, 2jae6 commented on LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
> +            $0.setTitleColor(.black, for: .normal)
flex.addItem()에 addSubView가 호출되는군요!! container는 addSubView제거했습니다. 하위 서브뷰들도 `addItem` 자동으로 addSubView되는지 한번 체크해볼게요!

2022-04-26 03:02 UTC, 2jae6 commented on LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
> +        }).disposed(by: disposeBag)
감사합니다. distinctUntilChanged는 중복된 이벤트가 방출되었을 때 하나만 받도록 하는것으로 알고있는데 여기서 필요한 이유가 있을까요???

2022-04-26 03:13 UTC, 2jae6 commented on LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
> +        animalButton.rx.tap.asDriver()
UI layer에 관련된 것일 경우 개인적으로 asDriver를 명시적으로 사용하고있습니다.
혹여나 main thread에서 돌아가야하는데 빠질 수도 있으니까요. 
말씀하신대로 내부 동작에는 UI 작업이 필요하지는 않아서 불필요해보입니다.
수정하겠습니다!

2022-04-26 03:16 UTC, 2jae6 commented on LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
> +        animalButton.rx.tap.asDriver()
수정 완료했습니다.

2022-04-26 03:24 UTC, 2jae6 commented
리뷰해주신 부분 참고해서 수정 완료했습니다. 확인 후 merge 부탁드려요!

2022-04-26 05:01 UTC, elppaaa commented on LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
> +        }).disposed(by: disposeBag)
습관적으로 적었네요 😮  없는 게 맞는 것 같아요!

2022-04-26 05:02 UTC, elppaaa approved these changes

2022-04-26 05:35 UTC, elppaaa commented on LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
> +            self.view.addSubview($0)
`view.addSubview` 가 아직 존재합니다 (˃̣̣̣̣︿˂̣̣̣̣ ) 
view hierarchy 를 보면 `flexLayoutContainer` 에서 `addItem` 이 호출될때 
추가된걸 확인할 수 있습니다 :]
신기하게 충돌은 안나네요 🦀 

<img width="200" alt="image" src="https://user-images.githubusercontent.com/15855011/165226962-b1332cf2-b0fe-480b-8a98-4b0429abd0c0.png">

2022-04-26 05:35 UTC, elppaaa commented on LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
> +            let liarGameVC = LiarGameViewController(subject: subject ?? .job)
`?? .job` 은 불필요해 보입니다!

2022-04-26 09:35 UTC, 2jae6 commented on LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
> +            self.view.addSubview($0)
네 확인했습니다.  
self.view.addSubview($0)
<img width="358" alt="스크린샷 2022-04-26 오후 6 33 42" src="https://user-images.githubusercontent.com/47078140/165270248-120b4ecf-3c81-4395-928a-8379aac70e42.png">

 self.view.addSubview($0)
self.view.addSubview($0) 
같은 요소 여러개 추가하는걸로 제가 테스트 해봤는데 동일 인스턴스는 아무리 추가해도 하나밖에 안되도록 애플에서 그렇게 만들었나보네요
수정 완료했습니다!

2022-04-26 09:36 UTC, 2jae6 commented on LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
> +            let liarGameVC = LiarGameViewController(subject: subject ?? .job)
넵 제거 완료했습니다 :)

2022-04-26 09:37 UTC, merged